// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KleinenijnProject
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Zoeken van pagina teksten op website Kleinenijn.nl")]
    public partial class ZoekenVanPaginaTekstenOpWebsiteKleinenijn_NlFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "KleinenijnFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("nl-NL"), "Zoeken van pagina teksten op website Kleinenijn.nl", "\tOm teskten op de kleinenijn site te zoeken\r\n\tAls een sitebeheerder\r\n\tWil ik auto" +
                    "matisch teksten kunnen controleren", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ga naar de Kleinenijn site en controleer pagina\'s")]
        [NUnit.Framework.CategoryAttribute("KleinenijnIntakeTest")]
        [NUnit.Framework.TestCaseAttribute("Kleinenijn.nl", "Welkom", "Huiselijk en vertrouwd", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kleinenijn.nl", "Foto\'s", "Foto\'s", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kleinenijn.nl", "Kosten", "Tarieven en wat u moet weten", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kleinenijn.nl", "Contact", "Contact", new string[0])]
        public virtual void GaNaarDeKleinenijnSiteEnControleerPaginaS(string website, string menuKnop, string paginaTekst, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "KleinenijnIntakeTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ga naar de Kleinenijn site en controleer pagina\'s", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given(string.Format("Ik ga naar de volgende pagina {0}", website), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gegeven ");
#line 9
    testRunner.And("Ik zie dat de pagina geladen is", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line 10
 testRunner.When(string.Format("Ik klik op de knop {0}", menuKnop), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line 12
 testRunner.Then(string.Format("Wordt de tekst {0} op een pagina van de site gevonden", paginaTekst), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
